name: Build Windows installer

on:
  push:
    branches: [ main ]

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build installer
        run: npm run build

      - name: Upload installer artifact
        uses: actions/upload-artifact@v2
        with:
          name: AutoBot-Windows-Installer
          path: dist/*.exe
